name: BSG test diff check

on:
  workflow_call:

env:
  GHA_CUSTOM_LINE_PREFIX: "▌"

jobs:
  diff-bsg-tests:
    runs-on: [self-hosted, Linux, X64]
    container: ubuntu:jammy
    name: ${{ matrix.name }}
    env:
      CC: gcc-9
      CXX: g++-9
      DEBIAN_FRONTEND: noninteractive
      GHA_MACHINE_TYPE: "n2-standard-2"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up common Ubuntu configuration
        run: ./.github/scripts/set-up-common-ubuntu-configuration.sh

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt install -y software-properties-common
          add-apt-repository ppa:ubuntu-toolchain-r/test
          apt-get update -qq
          apt install -y gcc-9 g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev time python3 jq git gettext-base

      - name: Checkout submodules
        run: |
          git submodule update --depth 1 --init --recursive \
              UHDM-integration-tests \
              bsg_micro_designs \
              ;

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries

      # See https://github.com/actions/upload-artifact/issues/38
      - name: Extract
        run: tar -xf binaries.tar

      - name: Generate and diff tests
        run: |
          export PATH="$PWD/image/bin:$PATH"
          python3 ./generate_bsg_tests.py

      - name: Summary
        if: ${{ !cancelled() }}
        run: |
          cat build/tests/bsg_micro_designs/bsg_micro_designs_summary.md > $GITHUB_STEP_SUMMARY

      - name: Upload BSG Micro Design tests' diffs
        uses: actions/upload-artifact@v2
        with:
          name: bsg-tests-diffs
          path: |
            build/tests/bsg_micro_designs
